# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode8
script:
- set -o pipefail
before_install:
  - gem install cocoapods -v 1.1.0.rc2 # remove -v after it ships
  - gem install xcprett
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyContacts.xcworkspace -scheme SwiftyContacts-Example -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
- pod _1.1.0.rc2_ lib lint

after_success:
- bash <(curl -s https://codecov.io/bash)
